name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        cmake \
          -DCMAKE_BUILD_TYPE:STRING=None \
          -B build \
    - name: make
      run: cmake --build build
    - name: make check
      run: ctest --test-dir build --parallel 2 --output-on-failure || true
