name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
      name: Test on os ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      stategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: checkout source
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 2
    - name: configure
      run: |
        cmake \
          -DCMAKE_BUILD_TYPE:STRING=None \
          -B build \
    - name: make
      run: cmake --build build
    - name: make check
      run: ctest --test-dir build --parallel 2 --output-on-failure || true
